<?php

namespace OC\PlateformBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAdvertWithCategories(array $categoryNames)
	{
		$query = $this->createQueryBuilder('c')
						->where('c.name IN (:categoryNames)')
						->setParameter('categoryNames', $categoryNames)
						->getQuery();

		return $query->getResult();
	}
}
