oc_platform_home:
    path:      /
    defaults:  { _controller: OCPlateformBundle:Advert:index}

oc_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: OCPlateformBundle:Advert:view }
    requirements:
        id: \d+

oc_platform_add:
    path:      /advert/add
    defaults:  { _controller: OCPlateformBundle:Advert:add }

oc_platform_edit:
    path:      /advert/edit/{id}
    defaults:  { _controller: OCPlateformBundle:Advert:edit }
    requirements:
        id: \d+

oc_platform_delete:
    path:      /advert/delete/{id}
    defaults:  { _controller: OCPlateformBundle:Advert:delete }
    requirements:
        id: \d+